### ISSUE TITLE
!play feature cannot play the Crab Rave

### ISSUE THREAD

**Issue by andrewd18** [SlickyCorp-Heavy-Manufacturing/SlickBot#98]
It is vitally important for the future of our nation that I be able to play the [Noisestorm - Crab Rave](https://www.youtube.com/watch?v=cE0wfjsybIQ) video in the voice channel. Slickbot sits in channel supposedly playing music but never makes a sound and never disconnects. This is the opposite of a Crab Rave and I am disappoint.

**Comment by krische** [comment]
This issue has been resolved
